package edu.uniquindio.co.tribooo.core.theme

import androidx.compose.ui.graphics.Color

// Paleta Material 3 del prototipo (tema claro)
val PrimaryLight = Color(0xFF00677D)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFB3EBFF)
val OnPrimaryContainerLight = Color(0xFF001F28)
val SecondaryLight = Color(0xFF4B6269)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE7EE)
val OnSecondaryContainerLight = Color(0xFF061F25)
val TertiaryLight = Color(0xFF575C7E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDEE0FF)
val OnTertiaryContainerLight = Color(0xFF141936)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val SurfaceLight = Color(0xFFF5FAFD)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF5F8)
val SurfaceContainerLight = Color(0xFFE7EDF1)
val SurfaceContainerHighLight = Color(0xFFE1E7EB)
val SurfaceContainerHighestLight = Color(0xFFDBE2E6)
val OnSurfaceLight = Color(0xFF171C1F)
val OnSurfaceVariantLight = Color(0xFF3F484B)
val OutlineLight = Color(0xFF6F797C)
val OutlineVariantLight = Color(0xFFBFC8CC)
val InverseSurfaceLight = Color(0xFF2B3134)
val InverseOnSurfaceLight = Color(0xFFECF2F5)

// Paleta Material 3 del prototipo (tema oscuro)
val PrimaryDark = Color(0xFF5FD4EF)
val OnPrimaryDark = Color(0xFF003543)
val PrimaryContainerDark = Color(0xFF004E5F)
val OnPrimaryContainerDark = Color(0xFFB3EBFF)
val SecondaryDark = Color(0xFFB2CBD2)
val OnSecondaryDark = Color(0xFF1D3439)
val SecondaryContainerDark = Color(0xFF334A50)
val OnSecondaryContainerDark = Color(0xFFCEE7EE)
val TertiaryDark = Color(0xFFBFC4EB)
val OnTertiaryDark = Color(0xFF292E4E)
val TertiaryContainerDark = Color(0xFF3F4466)
val OnTertiaryContainerDark = Color(0xFFDEE0FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceDark = Color(0xFF0F1417)
val SurfaceContainerLowestDark = Color(0xFF0A0F11)
val SurfaceContainerLowDark = Color(0xFF171C1F)
val SurfaceContainerDark = Color(0xFF1B2023)
val SurfaceContainerHighDark = Color(0xFF262B2E)
val SurfaceContainerHighestDark = Color(0xFF303539)
val OnSurfaceDark = Color(0xFFDEE3E7)
val OnSurfaceVariantDark = Color(0xFFBFC8CC)
val OutlineDark = Color(0xFF899295)
val OutlineVariantDark = Color(0xFF3F484B)
val InverseSurfaceDark = Color(0xFFDEE3E7)
val InverseOnSurfaceDark = Color(0xFF2B3134)
